// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsmjjqixnewynizytner.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzbWpqcWl4bmV3eW5penl0bmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTM5NzgsImV4cCI6MjA2NDk2OTk3OH0.bbWfMJ_ga8UsiwZfY4qQfop9MOSJIkF9nZEhgRoQZaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);